{{if .Values.autoscaler}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: {{.Values.name}}
 namespace: {{.Values.namespace}}
spec:
 maxReplicas: {{.Values.autoscaler.maxReplicas}}
 minReplicas: {{.Values.autoscaler.minReplicas}}
 scaleTargetRef:
  apiVersion: "apps/v2beta2"
  kind: Deployment
  name: {{.Values.name}}
 behavior:
  scaleDown:
   stabilizationWindowSeconds: 600
   policies:
     - type: Pods
       value: 1
       periodSeconds: 60
 metrics:
 - type: Resource
   resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: {{.Values.autoscaler.averageUtilization}}
 - type: Resource
   resource:
     name: memory
     target:
       type: Utilization
       averageValue: {{.Values.autoscaler.averageValue}}
{{- end}}