{{if eq .Values.ingress.enable "true"}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{.Values.name}}-dr
  namespace: {{.Values.namespace}}
spec:
  host: {{.Values.name}}
{{- end}}